server:
  port: 9090

spring:
  datasource:
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5432/restaurant_management
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
